### ISSUE TITLE
Daylight Saving Time not reflected in dashboard

### ISSUE THREAD

**Issue by 5fff** [seemoo-lab/AirGuard#18]
![Screenshot_20211222-170943.jpg](https://user-images.githubusercontent.com/12352983/147165148-883d70c4-f03c-415a-8070-5432729551a9.jpg)

Timezone: CDT
I took the screen shot after a while. But it is observed that the actual discovery time should have been displayed as 4:26 pm as there's Daylight Saving Time

Great work, thanks!

**Comment by Trup3s** [comment]
This looks more like an ui issue, since the date time representation is handled by the system. I think whats happening is that the "PM" part is cutoff to any prevent line wrapping. 
Perhaps we should switch to some icons and remove the "Frist Discovery" and "Last Seen" text to save space and prevent such issues.

**Comment by Sn0wfreezeDev** [comment]
I agree with @Trup3s that this is likely a date formatting issue. I would not switch to something without text. The text makes it easier to understand what is happening. Maybe the lines should be allowed to wrap. It does not look nice, but people might use different font sizes anyway
