### ISSUE TITLE
FP3: after update to 1.1.0 history is lost and no new findings (bug or feature?)

### ISSUE THREAD

**Issue by klic** [seemoo-lab/AirGuard#33]
After upgrading to 1.1.0 the history of found devices is lost, but also it does not find devices 1.0.6 (still) does find.

FP3 with LineageOS 18.1.

What else is helpful for you?

Klaus

**Comment by Sn0wfreezeDev** [comment]
Are you sure that the history is lost or is it just the filter that is applied? 
By default we now only show devices for which a notification has been sent. This means only devices which are marked as tracking devices will be shown

**Comment by klic** [comment]
Indeed I'm not... Probably this is because I don't seem to have trackers around me (no complaint ;-))
I did not use any filters, I was only confused because it doesn't show me any trackers at all that the old version used to show.

Maybe just my misconception, as nobody else does seem to experience this

**Comment by Sn0wfreezeDev** [comment]
It is intentional, because many users were confused about how many tracking devices were around them even though most were not actually tracking them.  So we are hoping that a general more limited view can help people to only see what is relevant. (Renaming the title would probably make this more clear)
