### ISSUE TITLE
iOS Support 

### ISSUE THREAD

**Issue by iMonZ** [seemoo-lab/AirGuard#37]
The app is much better than what Apple provide for iOS.
Is it possible to create an iOS version or cross platform version of this app?

**Comment by Sn0wfreezeDev** [comment]
It's technically impossible, because Apple blocks Bluetooth access to such a level. Basically the system would filter out all devices that send data with an Apple Company ID in their Bluetooth packets. Additionally, background access to Bluetooth does not allow scanning for other things than iBeacons
