### ISSUE TITLE
App won't detect my AirTag

### ISSUE THREAD

**Issue by FWeinb** [seemoo-lab/AirGuard#6]
Just tried this app and it isn't detecting my AirTag. It is paired with my iPhone and should be taking part in the find my network. I did some digging and saw that you are only listing for devices with the byte prefix (0x12, 0x19) but my AirTag is sending (0x07, 0x19) in the manufacture data. Here are some information about the manufacture data I could find https://adamcatley.com/AirTag#advertising-data. 

It looks like my AirTag isn't paired correctly (I did try to do that multiple times) or there are some other differences as it is sending the payload for unregistered devices. 

Any idea what it could be?

**Comment by Sn0wfreezeDev** [comment]
Well as long as an AirTag is nearby the setup iPhone it won't send any data that makes it *findable* in the Find My Network. 
So to get our app to find your AirTag you need to deactivate Bluetooth on your iPhone and wait a bit until the AirTag changes its state. 

If this is not the case, Apple might have changed something in a recent update. That would be quite weird though since the system should be backwards compatible to all iPhones since iOS 13 and not just the ones with iOS 15 or newer

**Comment by FWeinb** [comment]
> Well as long as an AirTag is nearby the setup iPhone it won't send any data that makes it findable in the Find My Network.

I thought AirTag will send this data always. I do get the AirTag now but playing a sound isn't working for me. But as you said in another issue that is expected as the AirTag is closing the connection pretty fast. 

Do you have some more documentation about the available Services on the AirTag?

This is the only source these Services/Characteristics are mentioned. 
https://github.com/seemoo-lab/AirGuard/blob/b1de251be65b27b04954ce4ca968113274874cd2/app/src/main/java/de/seemoo/at_tracking_detection/util/ble/BluetoothLeService.kt#L134-L137
