### ISSUE TITLE
[Bug] Do not use locations with a too high uncertainty

### ISSUE THREAD

**Issue by Sorunome** [seemoo-lab/AirGuard#76]
So, I have this airtag on an item at home for which I frequently get false alarms for tracking, despite it not moving with me. It seems to me like it is using for location also points reported by android which have a very high uncertainty, mainly those only used via triangulation of cell towers. Since those have a very high uncertainty (often >500m), it does not really make sense to use this as a location, and instead rely more on a gps fix or thelike (<20m uncertainty? <50m? dunno). That way most if not all of my false positives could be avoided

**Comment by BlackWolfWoof** [comment]
I noticed when I am at work / school that my location jumps to a nearby university around 500m away too. My coworkers have a lot of apple airpods following me from class to class in the same building, thats why it triggered a tracking alarm and i noticed this behaviour.
I don't know if thats just my phone doing weird stuff with my location or if that is due to a too inaccurate measurement the app deemed as ok to use.

**Comment by lbdroid** [comment]
It SHOULD use locations with high uncertainty, but in doing so, should make sure that the distance between the beacons exceeds the sum of the two accuracies.

**Comment by Sn0wfreezeDev** [comment]
We updated our detection algorithm and location fetching to adjust for this
